<?php
/*
    This file is part of Camdram.

    Camdram is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Camdram is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Camdram; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    
    Copyright (c) 2006-2012. See the AUTHORS file for a list of authors.
*/

$query = "SELECT * FROM acts_pages WHERE acts_pages.id = $currentid";
$page = sqlquery($query, $adcdb) or die(mysql_error());
$row_page = mysql_fetch_assoc($page);

if($row_page['mode']=='menuitem' && !isset($_GET[create])) {
   $currentid = intval($row_page[help]);
   if($currentid!=0) {
      $query = "SELECT * FROM acts_pages WHERE acts_pages.id = $currentid";
       $page = sqlquery($query, $adcdb) or die(mysql_error());
       $row_page = mysql_fetch_assoc($page);
   }
}


$row_menu = $row_page;
while ($row_menu['ghost'] != 0 && $row_menu['parentid']>0)
{
	$q = sqlquery("SELECT * FROM acts_pages WHERE id = " . $row_menu['parentid'], $adcdb) or die (mysql_error());
	$row_menu = mysql_fetch_assoc ($q);

	mysql_free_result($q);
}

$curpage = $row_page['id'];
$expand_tree = array();
do {
  $query = "SELECT id, parentid FROM acts_pages WHERE id=" . $curpage;
  $q = sqlquery ($query, $adcdb) or die ($query.": ".mysql_error());
  
  $row = mysql_fetch_assoc ($q);
  $expand_tree[$curpage] = 1;
  $curpage = $row['parentid'];
} while ($curpage != 0);
$section = $row['id'];
$me = $row_page['id'];

/** Prints out a div containing horizontal rss links.
 * @public
 */
function div_rss_horiz()
{
  global $row_page;
  if($row_page['rssfeeds']!="") {
    echo "<div id=\"rss\"><p>";
    $rssfeeds = explode(";",$row_page['rssfeeds']);
    $firstfeed = true;
    foreach($rssfeeds as $feed) {
      if(!$firstfeed) echo " | ";
      $firstfeed=false;
      echo "<a href=\"/rss.php?type=".$feed."\">RSS ".$feed." feed</a>";
    }
    echo "</p></div>";
  }
}

/** Prints out a div containing horizontal account links.
 * @public
 */
function div_account_horiz()
{
  echo "<div id=\"account\"><p>";
  if(logindetails(false,false,true)>0) 
  {
    unset($_GET['loginbox']);
    $loggedin=true;
  }
  echo "</p></div>";
}

/** Prints out a div containing horizontal admin links.
 * @public
 */
function div_admin_horiz()
{
  global $row_page, $currentid;
  
  if(hasEquivalentToken('security',-3) || (isset($_SESSION['ghostid']) && hasEquivalentToken('security',-3,$_SESSION['ghostid']) ))
  {
    echo "<div id=\"admin\">";
    echo("<p>Verbose: ");
    makeLink(0,"on",array("systemverbose"=>"on"));
    echo " | ";
    makeLink(0,"off",array("systemverbose"=>"off"));
    echo "<br/>";
    echo ("This is page $row_page[id]<br /> $row_page[usepage]<br />");
  
    echo "<small>".makeLinkText(87,"edit...",array("virtualid"=>$currentid),true)."</small><br/>";
    echo "</p>";
    echo "</div>";
  }
}

/** Prints out a div containing the help question mark.
 * @public
 */
function div_help()
{
  global $row_page;
  if($row_page['kbid']>0) {
    echo "<div id=\"help\"><p>";
    echo startLink($row_page['kbid'],array(),true,0,"",true); //force popup 
  ?>
  Click here for help with this page</a></p></div><?php }
}

/**
  * This displays a div inside the navbox with both page modes, and any links generated by the page
  * @public
*/
function div_links() {
	global $sidelinks, $modes, $mode_active,$mode_title;
	if (isset($sidelinks) || sizeof ($modes) > 0) {#

		echo "<div id=\"sidelinks\">";
		
		if ($mode_title != "")
			print "<p class=\"modetitle\">$mode_title</p>"; 
		echo "<ul>";
		if (sizeof ($modes) > 0)
		{
			foreach ($modes as $mode)
			{
				if ($mode_active != $mode['modeid'])
				{
					echo "<li class=\"mode\">";
					echo makeLink($mode['id'], $mode['text'], $mode['overrideParam'], $mode['clear'], $mode['tagpram'], $mode['nolinkifthispage'], $mode['extra_url'], $mode['microOnlyParam'], $mode['nomicro']);
					echo "</li>";
				}
				else
				{
					echo "<li class=\"modeselected\">";
					echo makeLinkContents($mode['id'], $mode['text']);
					echo "</li>";
				}
			}
		}
					 
		echo $sidelinks;
		echo "</ul></div>";
	}
}

/** Prints a "toptab" or "selected_toptab" div
 * @public
 * @param $topidorname The section to link to
 * @param $title Link text to use
 * @param $littlelinks An array of title=>page pairs to go as a submenu under the main title
 */
function makeTab($topidorname, $title, $littlelinks=array()) {
  global $currentid, $section;

  $topid=$topidorname;
  $topname = $topidorname;

  if(is_numeric($topname)) {
    // replace topname with correct name from db
    $topname = idToPage($topid);
  } else {
    // replace topid with correct id from db
    $topid = pageToId($topname);
  }
  
  if($section == $topid) {
    // should also be if it's a parent etc..
    echo '<div class="toptab selected"';
  } else { 
    
    echo '<div class="toptab"';
  }
  echo ' onMouseOver="if (isMouseLeaveOrEnter(event,this)) new Effect.BlindDown($(\'exptab'.$topid.'\'),{duration: 0.25});" onMouseOut="if (isMouseLeaveOrEnter(event, this)) new Effect.BlindUp($(\'exptab'.$topid.'\'),{duration: 0.1});">';
 
  
  if($littlelinks!=array()) {
    echo "<div id=\"exptab".$topid."\" style=\"display: none\">";
    $first = true;
    foreach($littlelinks as $ltitle=>$page) {
      if(!$first) echo " | ";
      makeLink($page,$ltitle, array(), true, "", false, "", array(), true);
      $first=false;
    }
    echo "</div>";
    
  }    
  /* FIXME: All these arguments are required so that we can share one database
   * across both branches. After merge, we can get rid of them. */
  makeLink ($topid, $title, array(), true, "", false, "", array(), true);

  echo "</div>";
}
?>
